# Generated by Django 4.0 on 2023-12-30 12:54

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lga_id', models.PositiveIntegerField()),
                ('lga_name', models.CharField(max_length=50, verbose_name='lga_name')),
                ('lga_description', models.TextField(verbose_name='lga_description')),
                ('date_entered', models.DateTimeField(auto_now=True, verbose_name='date_entered')),
                ('user_ip_address', models.GenericIPAddressField(verbose_name='user_ip_address')),
                ('entered_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=4, unique=True, verbose_name='name_abbr')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ward_id', models.PositiveIntegerField()),
                ('ward_name', models.CharField(max_length=50, verbose_name='ward_name')),
                ('ward_description', models.TextField(verbose_name='ward_description')),
                ('date_entered', models.DateTimeField(auto_now=True, verbose_name='date_entered')),
                ('user_ip_address', models.GenericIPAddressField(verbose_name='user_ip_address')),
                ('entered_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.lga')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.state')),
            ],
        ),
        migrations.CreateModel(
            name='PollingUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('polling_unit_id', models.PositiveIntegerField()),
                ('polling_unit_number', models.CharField(max_length=50, verbose_name='polling_unit_number')),
                ('polling_unit_name', models.CharField(max_length=50, verbose_name='polling_unit_name')),
                ('polling_unit_description', models.TextField(null=True, verbose_name='polling_unit_description')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='lat')),
                ('long', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='long')),
                ('date_entered', models.DateTimeField(auto_now=True, verbose_name='date_entered')),
                ('user_ip_address', models.GenericIPAddressField(null=True, verbose_name='user_ip_address')),
                ('entered_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.lga')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.state')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.ward')),
            ],
        ),
        migrations.AddField(
            model_name='lga',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.state'),
        ),
        migrations.CreateModel(
            name='AnnouncedPuResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.PositiveIntegerField()),
                ('date_entered', models.DateTimeField(auto_now=True, verbose_name='date_entered')),
                ('user_ip_address', models.GenericIPAddressField(null=True, verbose_name='user_ip_address')),
                ('entered_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
                ('lga', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='website.lga')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.party')),
                ('polling_unit', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='ward', chained_model_field='ward', on_delete=django.db.models.deletion.CASCADE, to='website.pollingunit')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.state')),
                ('ward', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='lga', chained_model_field='lga', on_delete=django.db.models.deletion.CASCADE, to='website.ward')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
